language: go

sudo: false

env:
  - GO111MODULE=on

go:
  - "1.11.13"
  - "1.12"
  - "1.13"
  - "1.14"

before_install:
  - cd ./tests
  - go mod tidy
  - go get github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
