language: go

sudo: false

go:
  - "1.11.13"
  - "1.12"
  - "1.13"
  - "1.14"
  - tip

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS sqlx_adapter_test;'
  - psql -c 'CREATE DATABASE sqlx_adapter_test;' -U postgres

script:
  - cd ./tests
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci

services:
  - mysql
  - postgresql
